### ISSUE TITLE
DropIn UI crash issue.

### ISSUE THREAD

**Issue by jagatappv** [braintree/braintree-android-drop-in#13] opened 2016-12-19 14:05 UTC
Hello Sir,

App gets crash on selecting payment method.

 Here is the version details I'm using :
 compile 'com.braintreepayments.api:drop-in:3.+'
Genymotion with OS version: 4.1.1

When I launch payment gateway and selected "Credit or Debit Card" It just crashed with the following logs
each time.

Please look into this issue.

Thanks

Error Logs
//-------------------------
 Exception while inflating <vector>
                                                                       org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
                                                                           at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:717)
                                                                           at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:654)
                                                                           at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:617)
                                                                           at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:745)
                                                                           at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:365)
                                                                           at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
                                                                           at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
                                                                           at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:723)
                                                                           at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
                                                                           at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
                                                                           at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
                                                                           at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
                                                                           at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:53)
                                                                           at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
                                                                           at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
                                                                           at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:525)
                                                                           at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74)
                                                                           at com.braintreepayments.api.dropin.AddCardActivity.onCreate(AddCardActivity.java:92)
                                                                           at android.app.Activity.performCreate(Activity.java:5008)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                                           at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                           at dalvik.system.NativeStart.main(Native Method)
12-19 19:31:24.385 12258-12258/com.org.studopoly D/AndroidRuntime: Shutting down VM
12-19 19:31:24.385 12258-12258/com.org.studopoly W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa6307288)
12-19 19:31:24.405 12258-12260/com.org.studopoly D/dalvikvm: GC_CONCURRENT freed 1868K, 9% free 20913K/22919K, paused 10ms+1ms, total 17ms
12-19 19:31:24.421 12258-12258/com.org.studopoly E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.org.studopoly/com.braintreepayments.api.dropin.AddCardActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                                       at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
                                                                       at android.content.res.Resources.loadDrawable(Resources.java:1918)
                                                                       at android.content.res.Resources.getDrawable(Resources.java:659)
                                                                       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
                                                                       at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:723)
                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
                                                                       at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
                                                                       at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
                                                                       at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
                                                                       at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:53)
                                                                       at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
                                                                       at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
                                                                       at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:525)
                                                                       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74)
                                                                       at com.braintreepayments.api.dropin.AddCardActivity.onCreate(AddCardActivity.java:92)
                                                                       at android.app.Activity.performCreate(Activity.java:5008)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                                       at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                       at android.os.Looper.loop(Looper.java:137) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                                    Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                                                                       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:877)
                                                                       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:818)
                                                                       at android.content.res.Resources.loadDrawable(Resources.java:1915)
                                                                       at android.content.res.Resources.getDrawable(Resources.java:659) 
                                                                       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374) 
                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200) 
                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188) 
                                                                       at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:723) 
                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193) 
                                                                       at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81) 
                                                                       at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:53) 
                                                                       at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205) 
                                                                       at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185) 
                                                                       at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:525) 
                                                                       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74) 
                                                                       at com.braintreepayments.api.dropin.AddCardActivity.onCreate(AddCardActivity.java:92) 
                                                                       at android.app.Activity.performCreate(Activity.java:5008) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                                       at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                       at android.os.Looper.loop(Looper.java:137) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by harirao001** [comment] 2016-12-19 15:53
+1
Having same issue.
Need solution.

Thanks :)

**Comment by sdcoffey** [comment] 2016-12-19 16:47
Hey @jagatappv  - thanks for letting us know! I'll look into this.

@harirao001 - are you also experiencing this issue with Genymotion, OS version 4.1.1?

**Comment by harirao001** [comment] 2016-12-20 08:27
Yeah getting same error.

**Comment by sdcoffey** [comment] 2016-12-21 01:20
@jagatappv @harirao001 

Are either of you using `com.android.support:appcompat-v7:23.2.0` in your apps? Seems like there have been some issues reported with this version causing a crash similar to yours. I was not able to reproduce this issue. 

See [this SO post](http://stackoverflow.com/questions/35668495/app-getting-crashed-and-i-am-not-able-to-understand-it).

**Comment by jagatappv** [comment] 2016-12-21 11:33
@sdcoffey 
I'm using latest version still getting issue.

Here is my version detail  :

 buildToolsVersion '24.0.1'
 compile 'com.android.support:appcompat-v7:24.2.1'

**Comment by sdcoffey** [comment] 2016-12-21 19:11
Thanks for the info @jagatappv. I'm still not able to reproduce this issue, though.

Can you give me some more details about your integration? What other dependencies are you declaring in your `build.gradle` file? Are you able to reproduce this issue on the stock (non-genymotion) android emulator, or a real device? If not, does the crash occur in any other OS versions of genymotion or just 4.1.1? Thanks in advance for helping us debug this!

**Comment by sdcoffey** [comment] 2017-01-10 17:01
I'm going to close this issue for non-activity. Please feel free to re-open if the issue persists.

**Closed by sdcoffey** 2017-01-10 17:01 UTC
