### ISSUE TITLE
Updating outdated MasterCard logo

### ISSUE THREAD

**Issue by mrsasha** [braintree/braintree-android-drop-in#47] opened 2017-09-15 09:35 UTC
Hi,

I noticed that you're still using the old MasterCard logo, which got changed last year. Can we get this updated please?

http://www.underconsideration.com/brandnew/archives/new_logo_and_identity_for_mastercard_by_pentagram.php
https://brand.mastercard.com/brandcenter/mastercard-brand-mark.html

Thanks!

**Comment by lkorth** [comment] 2017-09-15 19:22
Duplicate of braintree/android-card-form#34

**Closed by lkorth** 2017-09-15 19:22 UTC

**Comment by lkorth** [comment] 2017-09-15 20:07
Vaulted logos were updated in f48353f44dbda577877c0db95109d6b8d47aab43 and 0bf0fc1fa40bbf30a50330ca9e29eafaacba09d0
