### ISSUE TITLE
CardinalComm SDK 60 Warning Template - Id Bridging

### ISSUE THREAD

**Issue by faezmurshidi** [braintree/braintree-android-drop-in#373] opened 2022-12-01 04:31 UTC
### General information

* SDK/Library version: 5.+
* Environment: Production
* Android Version and Device: - 

### Issue description

We received email from Google Play Store title: CardinalComm SDK 60 Warning Template - Id Bridging
<img width="723" alt="Screenshot 2022-12-01 at 12 30 18 PM" src="https://user-images.githubusercontent.com/9053513/204966171-7abc50f8-197f-4a77-b2ce-13daabad9691.png">
 

Please help to assist

**Comment by mahendradabiaplite** [comment] 2022-12-01 05:53
Hi Developers at *************,
After a recent review, we found that your app  *************** is not compliant with one or more of our Developer Program Policies. Please resolve this issue within 60 days of the issuance of this notification or your new releases may be rejected or the app may be removed from Google Play. See below for more information about your app's status and how to correct the issue.
Reasons of violation
Issue with your app
Your app is using the Cardinal Mobile SDK which collects persistent device identifiers, but may not be limited to Android ID and hardware IDs. Persistent device identifiers may not be linked to any other personal and sensitive user data and/or resettable device identifiers (eg, IMEI, IMSI, SIM Serial #, etc).
You may consider upgrading to a policy-compliant version of this SDK, if available from your SDK provider or removing the SDK. According to your SDK provider, you may consider upgrading to 2.2.7-2. Please consult the SDK provider for further information. Google is unable to endorse or recommend any third party software.
Reasons of violation
About the User Data policy
If an app handles personal and sensitive user data, then the app developer must limit the access, collection, use, and sharing of personal and sensitive user data acquired through the app to app and service functionality and policy conforming purposes reasonably expected by the user.
Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers except for the purposes of:
Telephony linked to a SIM identity (eg, wifi calling linked to a carrier account), and
Enterprise device management apps using device owner mode.
These uses must be prominently disclosed to users as specified in the User Data policy.
Action required: Submit an updated app within 60 days
To help make sure that your app stays available on Google Play:
1. Read through the User Data policy for more details.
2. Make appropriate changes to your app, and be sure to address the issue identified above. In addition to your Production release, if you have other release types that you use for testing and/or quality assurance checks (for example, Internal test, Closed, Open), please make sure to update those tracks as well.
3. Check that your app is compliant with all other Developer Program Policies. Additional enforcement could occur if there are further policy violations.
4. Sign in to Play Console, upload the modified policy-compliant APK across all tracks, and deactivate the non-compliant APK(s).
5. Click Manage track > Create new release.
If the release with the violating app bundles / APKs are in a draft state, discard the release.
Otherwise, add the policy-compliant version of app bundles / APKs.
Make sure the non-compliant version is under the “Not Included“ section of this release.
Enter a release name and click Save. Once saved, click Review release, then proceed to roll out the release to 100%.
6. If the non-compliant versions are released to multiple tracks, repeat step 5 in each track.
7. Submit the update to your app.
Contact support
If you've reviewed the policy and feel our decision may have been in error, please reach out to our policy support team. We'll get back to you within 2 business days.
Learn more
Visit the Android Developers Blog to learn more about free tools and resources for building safe and successful apps.
Thanks for your continued support in helping to make Google Play a positive experience for both developers and consumers.
Please complete a two question survey to help us improve this experience.
The Google Play Team

**Comment by TcPhIo** [comment] 2022-12-01 12:17
We have also received this email regarding the Cardinal SDK.
Ive checked their site and they seem to have updated to address the policy issue on the 12 October 2022.
Is there an update to the braintree-android-drop-in package which includes this update?

we are currently implementing the most recent version found by the IDE (6.2.0)

**Comment by battagliandrea** [comment] 2022-12-01 14:00
Google requires Cardinal Mobile SDK 2.2.7-2 that has been updated with the last version of the sdk (6.4.0). 
Look this [commit](https://github.com/braintree/braintree-android-drop-in/commit/9746d070130ba84b85a09a54e75368233fa29f23)
In particular `org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk` is a transitive dependencies of `com.braintreepayments.api:three-d-secure` and if you run `./gradlew Drop-In:dependencies` you can see the following output:
```
+--- com.braintreepayments.api:three-d-secure:4.19.0
|    +--- org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-2
|    +--- androidx.appcompat:appcompat:1.3.1 (*)
|    +--- androidx.lifecycle:lifecycle-runtime:2.3.0 -> 2.4.1 (*)
|    +--- com.braintreepayments.api:braintree-core:4.19.0 (*)
|    \--- com.braintreepayments.api:card:4.19.0
|         +--- com.braintreepayments.api:braintree-core:4.19.0 (*)
|         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.32 -> 1.6.10 (*)
|         \--- androidx.annotation:annotation:1.2.0
```

So I think that updating of the sdk to 6.4.0 version should resolve the google's warning. 
I did the same on my own project and I hope that it'll work.

**Comment by dimitradg** [comment] 2022-12-01 15:05
> Google requires Cardinal Mobile SDK 2.2.7-2 that has been updated with the last version of the sdk (6.4.0). Look this [commit](https://github.com/braintree/braintree-android-drop-in/commit/9746d070130ba84b85a09a54e75368233fa29f23) In particular `org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk` is a transitive dependencies of `com.braintreepayments.api:three-d-secure` and if you run `./gradlew Drop-In:dependencies` you can see the following output:
> 
> ```
> +--- com.braintreepayments.api:three-d-secure:4.19.0
> |    +--- org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-2
> |    +--- androidx.appcompat:appcompat:1.3.1 (*)
> |    +--- androidx.lifecycle:lifecycle-runtime:2.3.0 -> 2.4.1 (*)
> |    +--- com.braintreepayments.api:braintree-core:4.19.0 (*)
> |    \--- com.braintreepayments.api:card:4.19.0
> |         +--- com.braintreepayments.api:braintree-core:4.19.0 (*)
> |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.32 -> 1.6.10 (*)
> |         \--- androidx.annotation:annotation:1.2.0
> ```
> 
> So I think that updating of the sdk to 6.4.0 version should resolve the google's warning. I did the same on my own project and I hope that it'll work.

Ηello, when you are saying update the sdk to 6.4.0, to which sdk you are referring to?

**Comment by dimitradg** [comment] 2022-12-01 15:25
> > > Google requires Cardinal Mobile SDK 2.2.7-2 that has been updated with the last version of the sdk (6.4.0). Look this [commit](https://github.com/braintree/braintree-android-drop-in/commit/9746d070130ba84b85a09a54e75368233fa29f23) In particular `org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk` is a transitive dependencies of `com.braintreepayments.api:three-d-secure` and if you run `./gradlew Drop-In:dependencies` you can see the following output:
> > > ```
> > > +--- com.braintreepayments.api:three-d-secure:4.19.0
> > > |    +--- org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-2
> > > |    +--- androidx.appcompat:appcompat:1.3.1 (*)
> > > |    +--- androidx.lifecycle:lifecycle-runtime:2.3.0 -> 2.4.1 (*)
> > > |    +--- com.braintreepayments.api:braintree-core:4.19.0 (*)
> > > |    \--- com.braintreepayments.api:card:4.19.0
> > > |         +--- com.braintreepayments.api:braintree-core:4.19.0 (*)
> > > |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.32 -> 1.6.10 (*)
> > > |         \--- androidx.annotation:annotation:1.2.0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So I think that updating of the sdk to 6.4.0 version should resolve the google's warning. I did the same on my own project and I hope that it'll work.
> > 
> > 
> > Ηello, when you are saying update the sdk to 6.4.0, to which sdk you are referring to?
> 
> [this one ](https://github.com/braintree/braintree-android-drop-in/releases)

Oh yeah sorry my bad. Thank you!

**Comment by sshropshire** [comment] 2022-12-01 15:31
@faezmurshidi @mahendradabiaplite @TcPhIo @battagliandrea @dimitradg thanks all for using the Braintree SDK for Android. As mentioned upgrading to the latest [6.4.0](https://github.com/braintree/braintree-android-drop-in/blob/master/CHANGELOG.md#640) version will include a version of Cardinal that is compliant with Google Play Store policies.

I'll close this issue. If something else comes up, please feel free to open another GitHub issue.

**Comment by bm185178** [comment] 2022-12-01 15:34
I have used [6.4.0](https://github.com/braintree/braintree-android-drop-in/blob/master/CHANGELOG.md#640) and 4.19 but it has issue with https://github.com/braintree/braintree_android/issues/624

**Comment by sshropshire** [comment] 2022-12-01 15:37
Ok I'm realizing now Google Play is warning on Cardinal 2.2.7-2. The email from Google does have unclear wording. It seems like Google is saying `2.2.7-2` is compliant.

I'll reach out to Cardinal and report back here when I have more information.

**Comment by sshropshire** [comment] 2022-12-01 16:27
@bm185178 Before I reach out to Cardinal, have you tried submitting with `6.4.0`? And do you get the same Google Play warning?

We'll be releasing an update to DropIn soon to depend on `4.20.0`, but this issue should be resolved in DropIn version `6.4.0` since Braintree Core SDK `4.19.0` depends on Cardinal `2.2.7-2`.

The `4.20.0` recommendation in #371 is to _always update to the latest version of our SDKs when possible_. We're working to resolve an internal compilation issue for DropIn to officially support `4.20.0` (PR [here](https://github.com/braintree/braintree-android-drop-in/pull/372)).

**Comment by mahendradabiaplite** [comment] 2022-12-01 16:40
> @bm185178 Before I reach out to Cardinal, have you tried submitting with `6.4.0`? And do you get the same Google Play warning?
> 
> We'll be releasing an update to DropIn soon to depend on `4.20.0`, but this issue should be resolved in DropIn version `6.4.0` since Braintree Core SDK `4.19.0` depends on Cardinal `2.2.7-2`.
> 
> The `4.20.0` recommendation in #371 is to _always update to the latest version of our SDKs when possible_. We're working to resolve an internal compilation issue for DropIn to officially support `4.20.0` (PR [here](https://github.com/braintree/braintree-android-drop-in/pull/372)).

@sshropshire Upgraded the version and submitted on play console It's in review will let you know once It gets approved.

**Comment by fradev94** [comment] 2022-12-01 19:34
I submit my app with 'com.braintreepayments.api:drop-in:6.4.0' and I receveid the same email from Google.

**Comment by sshropshire** [comment] 2022-12-01 21:00
Thanks all. We're investigating the issue and should have an update in the coming days. We appreciate your patience in the meantime.

**Comment by hollabaq86** [comment] 2022-12-02 16:07
Hi folks, can I get 👍 reactions from folks getting these emails that:
1. You are on the latest version (6.4.0)
2. The text of the email from the Google Playstore **specifically mentions the following:**
>Your app is using the Cardinal Mobile SDK which collects persistent device identifiers, but may not be limited to Android ID and hardware IDs. Persistent device identifiers may not be linked to any other personal and sensitive user data and/or resettable device identifiers (eg, IMEI, IMSI, SIM Serial #, etc).

If the contents of the email you're getting from Google is different, please drop that in a comment here or [contact Support](https://developer.paypal.com/braintree/help) referencing this issue.

We need a solid confirmation of this info so that we're correctly escalating the issue and that version 2.2.7-2 of Cardinal's SDK indeed does not resolve these alerts. Thanks all for your patience as we try to resolve this 🙏

**Comment by hollabaq86** [comment] 2022-12-02 16:10
I also want to mention that we are actively trying to reproduce these notifications with a demo app, too, but in the interest of the urgency of this issue we're asking for your help in confirming a few things. Thanks!

**Comment by hollabaq86** [comment] 2022-12-02 17:09
for internal tracking, issue 1456

**Comment by yosilevy** [comment] 2022-12-06 07:28
Any updates on this issue? What is the solution that is acceptable by Google?

**Comment by sshropshire** [comment] 2022-12-06 21:26
Hi all. Thanks for your patience while we escalated this issue to Cardinal and Google. Both Cardinal and Google have confirmed that **version 2.2.7-2 of the Cardinal Commerce SDK is compliant.**

Cardinal has advised folks to **try updating all versions of your app in all tracks** (Internal / Closed / Open testing and Production) to use the latest version of our DropIn SDK -> [6.5.0](https://github.com/braintree/braintree-android-drop-in/blob/master/CHANGELOG.md#650). Google emphasized that "**_all_** active versions of the app on **_any_** track need to be compliant."

If your application continues to be impacted after performing the above, [file an appeal](https://support.google.com/googleplay/android-developer/contact/protectappeals) with the Google Play store mentioning that your app depends on version `2.2.7-2` of the Cardinal SDK, which is compliant.

If you're still unable to deploy an update, let us know so we can keep track of issue resolution.

**Comment by uddyami** [comment] 2023-01-25 16:12
will this be fixed with 5.4.0?

**Comment by sshropshire** [comment] 2023-01-25 16:49
Hi yes, the [latest DropIn version](https://github.com/braintree/braintree-android-drop-in/issues/373) and version [5.4.0](https://github.com/braintree/braintree-android-drop-in/blob/master/CHANGELOG.md#540) now both depend on Cardinal 2.2.7-2.

**Closed by sshropshire** 2023-01-25 16:49 UTC
Labels: triaged

**Comment by niravtopsy** [comment] 2023-01-27 06:18
Hello Guys,

I am using braintree latest version 'com.braintreepayments.api:drop-in:6.6.0'

But I got the same issue/warning yesterday. What should I do to fix it?

Issue with your app
Your app is using the Cardinal Mobile SDK which collects persistent device identifiers, but may not be limited to Android ID and hardware IDs. Persistent device identifiers may not be linked to any other personal and sensitive user data and/or resettable device identifiers (e.g., IMEI, IMSI, SIM Serial #, etc).You may consider upgrading to a policy-compliant version of this SDK, if available from your SDK provider or removing the SDK. According to your SDK provider, you may consider upgrading to 2.2.7-2. Please consult the SDK provider for further information. Google is unable to endorse or recommend any third party software.

**Comment by sshropshire** [comment] 2023-01-27 16:56
Hi @niravtopsy make sure all tracks (e.g. alpha, beta, internal, production) in the Google Play store use the updated version of DropIn and the issue should be resolved.

**Comment by hashirawan01** [comment] 2023-05-31 14:11
@bat-eng sir i remove brainstree dependecy in my project but play store still reject my application after giving this warning.
