### ISSUE TITLE
AndroidManifest exception with PayPal 

### ISSUE THREAD

**Issue by kenny128** [braintree/braintree-android-drop-in#63] opened 2018-02-01 05:05 UTC
### General information

* SDK/Library version: 3.2.0
* Environment: Sandbox
* Android Version and Device: Android 6.0 Nexus 5 Emulator (x86_64)

### Issue description

I'm trying to implement braintree using drop in UI in xamarin.forms. By doing so I created a dependency service to use the respective code for iOS or Android. Starting out with the android implementation, I started with getting a package of bindings that allow me to call the functions in Android v2 SDK. Everything seem to work except for PayPal Integration. 

![image](https://user-images.githubusercontent.com/8788644/35661614-1321544a-075f-11e8-9d27-755efc5708bb.png)

attempting to click on the paypal button will not result in any activity appearing and onActivityResult gets called with a first user result code with the exception `Com.Braintreepayments.Api.Exceptions.BraintreeException: BraintreeBrowserSwitchActivity missing, incorrectly configured in AndroidManifest.xml or another app defines the same browser switch url as this app. See https://developers.braintreepayments.com/guides/client-sdk/android/v2#browser-switch for the correct configuration`

Not being able to debug into why I got the exception I was able to emulate the checks - `isManifestValid`

Within `isManifestValid` I was able to retrieve the `ActivityInfo `for `BraintreeBrowserSwitchActivity`
and it only returned false because `AppHelper.isIntentAvailable(fragment.getApplicationContext(), intent)` is false

Within `isIntentAvailable` `context.getPackageManager().queryIntentActivities(intent, 0)` returned an empty list making me think that the Intent is not registered to use any activity despite having declared the URL scheme in my AndroidManifest file.

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionName="1.3.16" package="com.company.abcmobileapp.android" android:installLocation="auto" android:versionCode="24">
	<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="23" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.USE_FINGERPRINT" />
  <uses-permission android:name="com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY" />
	<application android:debuggable="false" android:label="ABC" android:theme="@android:style/Theme.Holo.Light" android:icon="@drawable/appicon" android:largeHeap="true" android:hardwareAccelerated="false">
    <activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
    android:launchMode="singleTask">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="com.company.abcmobileapp.android.braintree" />
      </intent-filter>
    </activity>
  </application>
	<activity android:name="ShareActivity">
		<intent-filter>
			<action android:name="android.intent.action.SEND" />
			<category android:name="android.intent.category.DEFAULT" />
			<data android:mimeType="image/*" />
		</intent-filter>
	</activity>
</manifest>
```

Is there any suggestions as to what I can do to further debug or fix the issue? Any help is greatly appreciated, Thanks.

**Comment by sdcoffey** [comment] 2018-02-01 19:27
Hey @kenny128,

Thanks for opening this bug report. We don't _officially_ support Xamarin as an integration method, but I think we can probably figure out what's going on. The first thing to note (though it's probably unrelated) is that your `ShareActivity` is declared outside the `application` declaration.

Your manifest looks correct to me, would you mind for a sanity check, replacing `<data android:scheme="com.company.abcmobileapp.android.braintree" />` in your `intent-filter` with `<data android:scheme="${applicationId}.braintree" />`?

**Comment by kenny128** [comment] 2018-02-01 23:56
@sdcoffey Thanks for your reply and good pick on the `ShareActivity`,  I have tried ${applicationId} in place of the package name however maybe the ShareActivity not at the right place might affect it... I'll try that and edit the outcome on the comment.

**Comment by kenny128** [comment] 2018-02-02 00:27
On build xamarin adds a whole bunch of stuff in the AndroidManifest. Going through it myself I can't see what could possibly affect it but maybe it would be helpful

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionName="1.3.16" package="com.company.abcmobileapp.android" android:installLocation="auto" android:versionCode="24">
  <uses-sdk android:minSdkVersion="15" android:targetSdkVersion="23" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.USE_FINGERPRINT" />
  <uses-permission android:name="com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-feature android:name="android.hardware.camera" android:required="false" />
  <uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />
  <application android:debuggable="false" android:label="ABC" android:theme="@android:style/Theme.Holo.Light" android:icon="@drawable/appicon" android:largeHeap="true" android:hardwareAccelerated="false" android:name="md52756a63cade81005e12b999f52fa0153.MainApplication" android:allowBackup="true">
    <activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity" android:launchMode="singleTask">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="com.company.abcmobileapp.android.braintree" />
      </intent-filter>
    </activity>
    <activity android:name="ShareActivity">
      <intent-filter>
        <action android:name="android.intent.action.SEND" />
        <category android:name="android.intent.category.DEFAULT" />
        <data android:mimeType="image/*" />
      </intent-filter>
    </activity>
    <activity android:label="BrainTreeActivity" android:name="md52756a63cade81005e12b999f52fa0153.BrainTreeActivity" />
    <activity android:configChanges="orientation|screenSize" android:label="ABC" android:name="md52756a63cade81005e12b999f52fa0153.MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:host="content.company.com.au" />
        <data android:pathPrefix="/" />
        <data android:scheme="https" />
      </intent-filter>
    </activity>
    <activity android:configChanges="orientation|screenSize" android:label="ABC" android:noHistory="true" android:theme="@style/Theme.Splash" android:name="md52756a63cade81005e12b999f52fa0153.SplashScreen">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
    <activity android:label="Login" android:name="md53ec94fdcf571d649b55e7662efbba392.LoginActivity" />
    <activity android:label="SectionActivity" android:name="md53ec94fdcf571d649b55e7662efbba392.SectionActivity" />
    <activity android:configChanges="orientation|screenSize" android:label="Upload to ABC" android:launchMode="singleTop" android:name="md53ec94fdcf571d649b55e7662efbba392.ShareExtActivity">
      <intent-filter>
        <action android:name="android.intent.action.SEND" />
        <category android:name="android.intent.category.BROWSABLE" />
        <category android:name="android.intent.category.DEFAULT" />
        <data android:mimeType="*/*" />
      </intent-filter>
    </activity>
    <activity android:configChanges="orientation|screenSize" android:name="md51299d80e9f3428956bdee05a7b120580.MediaPickerActivity" />
    <service android:name="md59f70a99687498e7ba187118950981d26.KeepAliveService" />
    <activity android:label="Web Authenticator" android:name="md53c585be971e02235139fd1aef11fc0c1.FormAuthenticatorActivity" />
    <activity android:label="Web Authenticator" android:name="md53c585be971e02235139fd1aef11fc0c1.WebAuthenticatorActivity" />
    <activity android:label="@string/title_activity_webview" android:theme="@android:style/Theme.DeviceDefault" android:name="md53c585be971e02235139fd1aef11fc0c1.WebViewActivity" />
    <activity android:label="Web Authenticator Native Broswer" android:launchMode="singleTop" android:noHistory="true" android:name="md53c585be971e02235139fd1aef11fc0c1.WebAuthenticatorNativeBrowserActivity" />
    <receiver android:name="md53c585be971e02235139fd1aef11fc0c1.CustomTabsActionsBroadcastReceiver" />
    <provider android:name="mono.MonoRuntimeProvider" android:exported="false" android:initOrder="2147483647" android:authorities="com.company.abcmobileapp.android.mono.MonoRuntimeProvider.__mono_init__" />
    <!--suppress ExportedReceiver-->
    <receiver android:name="mono.android.Seppuku">
      <intent-filter>
        <action android:name="mono.android.intent.action.SEPPUKU" />
        <category android:name="mono.android.intent.category.SEPPUKU.com.company.abcmobileapp.android" />
      </intent-filter>
    </receiver>
    <activity android:name="com.braintreepayments.api.AndroidPayActivity" android:theme="@style/bt_transparent_activity" />
    <activity android:name="com.braintreepayments.api.GooglePaymentActivity" android:theme="@style/bt_transparent_activity" />
    <activity android:name="com.braintreepayments.api.threedsecure.ThreeDSecureWebViewActivity" />
    <service android:name="com.braintreepayments.api.internal.AnalyticsIntentService" />
    <activity android:name="com.braintreepayments.api.threedsecure.ThreeDSecureWebViewActivity" android:theme="@style/bt_three_d_secure_theme" />
    <activity android:name="com.braintreepayments.api.dropin.DropInActivity" android:theme="@style/bt_drop_in_activity_theme" />
    <activity android:name="com.braintreepayments.api.dropin.AddCardActivity" android:theme="@style/bt_add_card_activity_theme" />
    <activity android:name="io.card.payment.CardIOActivity" android:configChanges="keyboardHidden|orientation" />
    <activity android:name="io.card.payment.DataEntryActivity" />
    <meta-data android:name="android.arch.lifecycle.VERSION" android:value="27.0.0-SNAPSHOT" />
    <meta-data android:name="android.support.VERSION" android:value="26.1.0" />
    <activity android:name="com.google.android.gms.common.api.GoogleApiActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:exported="false" />
    <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
  </application>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.VIBRATE" />
</manifest>
```

**Comment by sdcoffey** [comment] 2018-02-13 21:45
Hey @kenny128,

Trying to reproduce this issue here, can you verify that you're using [this binding](https://github.com/NAXAM/braintreedropin-android-binding) of Drop-in?

**Comment by kenny128** [comment] 2018-02-15 01:31
@sdcoffey Oh i feel so stupid right now... Testing on and actual device actually worked. Testing on a colleagues' simulator also works which was very odd to me. I still can't figure out why it isn't working on my simulator and its working on pretty much everything else.

**Comment by sdcoffey** [comment] 2018-02-15 15:56
@kenny128,

No problem! I'm going to close this issue since it seems it's working at least in some places, but I would recommend, if you haven't already tried this, to destroy and recreate the emulator you're using. Sometimes they can get into a bad state. Let me know if that works!

**Closed by sdcoffey** 2018-02-15 15:56 UTC

**Comment by kenny128** [comment] 2018-02-16 03:12
Recreating the emulator fixed it. Definitely not something I would have thought to try.

**Comment by Samuthirat** [comment] 2024-12-26 11:30
Original Error: No meta data found with key: AccessoryServicesLocation in zedTarc.zig.zig

Issue Description: I'm encountering an issue where after a payment is made via PayPal(Braintree), the process isn't returning to the app. The error occurs because of the package name being zedTarc.zig.zig in camel case. Here is the <intent-filter> I have defined:

<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="zedTarc.zig.zig.braintree" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
</intent-filter>


The log also shows this error:
2024-12-26 16:54:20.179 6881-10070 SG::OCSCacheHelper com.oplus.pantanal.ums E checkFromPackageReceiver resolvedInfo is empty, pkg = zedTarc.zig.zig [UMS.apk|com.oplus.pantanal.ums|1.4.12-3303787]
2024-12-26 16:54:25.956 22987-22987 OplusInput...erInternal app.art.com D get inputMethodManager extension: com.android.internal.view.IInputMethodManager$Stub$Proxy@f752063
2024-12-26 16:57:36.599 25791-25890 WM-WorkerWrapper zedTarc.zig.zig I Worker result SUCCESS for Work [ id=d4118a6e-cc7b-4d0b-af82-3192eaa1425f, tags={ com.datadog.android.core.internal.data.upload.UploadWorker, DatadogBackgroundUpload } ]

Can anyone help me understand why this is happening and how I can fix it?
