### ISSUE TITLE
Issue with your app : Google play console warning.

### ISSUE THREAD

**Issue by niravtopsy** [braintree/braintree-android-drop-in#394] opened 2023-01-27 08:19 UTC
I got the warning from the play store :

Issue with your app

Your app is using the Cardinal Mobile SDK which collects persistent device identifiers, but may not be limited to Android ID and hardware IDs. Persistent device identifiers may not be linked to any other personal and sensitive user data and/or resettable device identifiers (e.g., IMEI, IMSI, SIM Serial #, etc).You may consider upgrading to a policy-compliant version of this SDK, if available from your SDK provider or removing the SDK. According to your SDK provider, you may consider upgrading to 2.2.7-2. Please consult the SDK provider for further information. Google is unable to endorse or recommend any third party software.

My Braintree dropin version is :

'com.braintreepayments.api:drop-in:6.6.0'

Which action now we have to take on it?

**Comment by we-prajapati-c001** [comment] 2023-01-27 08:28
Semms duplicate of https://github.com/braintree/braintree-android-drop-in/issues/373

**Comment by niravtopsy** [comment] 2023-01-27 08:56
@we-prajapati-c001 That issue closed there, so I opened a new one.

**Comment by we-prajapati-c001** [comment] 2023-01-27 09:11
It was closed yesterday only

**Comment by niravtopsy** [comment] 2023-01-27 09:30
@we-prajapati-c001 I app live on play store with latest version but still i am getting the same issue, you know the solutions?

**Comment by we-prajapati-c001** [comment] 2023-01-27 09:31
I might be able to help, how many open tracks do you have?

**Comment by niravtopsy** [comment] 2023-01-27 09:33
Open track mean?

**Comment by we-prajapati-c001** [comment] 2023-01-27 09:35
You have internal testing, beta, etc. tracks no

**Comment by we-prajapati-c001** [comment] 2023-01-27 09:36
And does all of them include latest build?

**Comment by niravtopsy** [comment] 2023-01-27 09:54
In open testing and production, These two track contains the latest build.

**Comment by we-prajapati-c001** [comment] 2023-01-27 11:02
still, getting the error? https://github.com/braintree/braintree-android-drop-in/issues/373#issuecomment-1340028609 then file an appeal I guess.

**Comment by niravtopsy** [comment] 2023-01-27 11:04
It is Required upload latest build in all the track?

**Comment by we-prajapati-c001** [comment] 2023-01-27 11:10
Yes all OPEN tracks

**Comment by we-prajapati-c001** [comment] 2023-01-27 12:30
Were you able to fix it?

**Comment by niravtopsy** [comment] 2023-01-27 13:08
I will upload new build for open and close testing and let's see i will fix or not.

**Comment by we-prajapati-c001** [comment] 2023-01-27 14:15
@niravtopsy Please keep us updated

**Comment by niravtopsy** [comment] 2023-01-27 14:26
sure, and thanks

**Comment by sshropshire** [comment] 2023-01-27 15:19
Hi all. Thanks for using the Braintree SDK for Android. Please see the resolution in [#373](https://github.com/braintree/braintree-android-drop-in/issues/373#issuecomment-1340028609). As @we-prajapati-c001 mentioned all open tracks need to be updated to clear the warning.

**Closed by sshropshire** 2023-01-27 15:19 UTC
