### ISSUE TITLE
DataBinderMapperImpl() is not generated

### ISSUE THREAD

**Issue by novotnyfra** [braintree/braintree-android-drop-in#72] opened 2018-04-05 16:11 UTC
### General information

* SDK/Library version: 3.3.0
* Gradle Plugin Version: **3.1.0**

### Issue description

_com.braintreepayments.api.DataBinderMapperImpl()_ is not generated when using Data Binding Compiler V2.

Error:
`error: cannot find symbol
    addMapper(new com.braintreepayments.api.DataBinderMapperImpl());
  symbol:   class DataBinderMapperImpl
  location: package com.braintreepayments.api`

**Comment by rav3n** [comment] 2018-04-18 11:29
I have a similar problem
Error:(7, 44) error: cannot find symbol class DataBinderMapperImpl

**Comment by bluk** [comment] 2018-04-18 15:46
Hi, do you have a setting like `android.databinding.enableV2=true` in your `gradle.properties` or are you using `kotlin-kapt`?

**Comment by novotnyfra** [comment] 2018-04-18 20:42
yes, I have Daba Binding Compiler v2 enabled as you mentioned and I!m also using `kotlin-kapt`.
Drop-in is working when `android.databinding.enableV2=false`, but it is not the solution.

**Comment by MrRexZ** [comment] 2018-04-23 09:29
I'm getting this issue as well after enabling `android.databinding.enableV2=true`. Unfortunately for v1 has some bugs in my setup (Android Studio 3.1 stable and gradle 4.4 )

**Comment by sdcoffey** [comment] 2018-05-16 23:54
Hey y'all,

We were finally able to reproduce this issue. WIll begin working on a fix - just wanted to keep you updated.

**Comment by sdcoffey** [comment] 2018-05-17 17:16
Alright @novotnyfra, @rav3n, @MrRexZ,

I was able to chase this issue down to one of our internal dependencies for [braintree_android](https://github.com/braintree/braintree_android), specifically our [visa checkout dependency](https://github.com/braintree/braintree-android-visa-checkout), which uses [data binding](https://github.com/braintree/braintree-android-visa-checkout/blob/master/VisaCheckout/build.gradle#L11). The issue with databinding v2 is described at a high level [in the Android Developer docs](https://developer.android.com/topic/libraries/data-binding/start).

Specifically, this note:
> Note: The new data binding compiler in the Android Plugin version 3.1 is not backwards compatible. You need to generate all your binding classes with this feature enabled to take advantage of incremental compilation. However, the new compiler in the Android Plugin version 3.2 is compatible with binding classes generated with previous versions. The new compiler in version 3.2 is enabled by default.

Because we're building our visa-checkout module with gradle plugin version 3.1, apps that are enabling databinding v2 will not be able to compile any package that pulls in `visa-checkout`, i.e., `braintree-android`, and `braintree-android-drop-in`.

Our recommendation for the time being is to use the workaround described above until version 3.2 of the android gradle plugin is released, at which time we can upgrade our visa checkout library to ensure full backwards compatibility. We can't release a new version in the interim as it may cause undesirable downstream effects for folks using this library.

I'm going to close this issue in favor of [this issue](https://github.com/braintree/braintree-android-visa-checkout/issues/1) in `braintree-android-visa-checkout` related to updating our gradle plugin.

Thanks for your patience!

**Closed by sdcoffey** 2018-05-17 17:16 UTC

**Comment by sdcoffey** [comment] 2018-05-23 16:06
Hey @novotnyfra, @rav3n, @MrRexZ,

Quick update for y'all. @lkorth mentioned to me this morning that there's a workaround for this issue if you're using Braintree 2.12 or above. Just change your dependency in your `build.gradle` to look like

```groovy
implementation('com.braintreepayments.api:braintree:2.13.0') {
    exclude group: 'com.braintreepayments.api', module: 'visa-checkout'
}
```

And it will compile for you. The obvious exception is if you're using VisaCheckout, in which case you'll need to wait for the fix in the above tagged issue. Let me know if that works for you!
