### ISSUE TITLE
How set amount of money 

### ISSUE THREAD

**Issue by MohammedTohamyGazzar** [braintree/braintree-android-drop-in#449] opened 2023-10-18 07:34 UTC
### Braintree SDK Version

last version

### Environment

Sandbox

### Android Version & Device

12

### Braintree dependencies

  implementation 'com.braintreepayments.api:drop-in:6.13.0'

### Describe the bug

after get nounce how set amount

### To reproduce

give a simple example and completed

### Expected behavior

I get nounce then can't complete or set amount

**Comment by sarahkoop** [comment] 2023-10-18 13:56
Hi @MohammedTohamyGazzar - Thanks for using the Braintree Android Drop-in SDK! Please refer to our [developer docs](https://developer.paypal.com/braintree/docs/start/hello-server/ruby) for a guide to transacting with the nonce on your server. Closing this issue as it is not a bug in the SDK - please feel free to reach out to our technical support for questions regarding your specific integration.

**Closed by sarahkoop** 2023-10-18 13:56 UTC
