### ISSUE TITLE
Drop In wont able back to app

### ISSUE THREAD

**Issue by Chaos2805** [braintree/braintree-android-drop-in#436] opened 2023-08-24 10:04 UTC
### Braintree SDK Version

6.11.0

### Environment

Sandbox

### Braintree dependencies

[NA](com.braintreepayments.api:drop-in:6.11.0

### Describe the bug

For my case, I upgrade drop-in SDK from 6.5.0 to 6.11.0, and i found that previously BraintreeClient will convert default params to lowercase, and now it removed.
![image](https://github.com/braintree/braintree-android-drop-in/assets/21195683/8df81ccb-2e22-4fb4-97da-f4a197acde2f)
In my application the applicationId contains capital letter, I think the scheme is not accepting capital case, since it prompt AppLinkUrlError if I put capital for android:scheme.

I found the BrainTreeClient constructor able to pass the custom url scheme, but on top DropInClient not able to modify the setting of BrainTreeClient
![image](https://github.com/braintree/braintree-android-drop-in/assets/21195683/79e911b6-8cfc-4586-8c2d-5793552e411d)

### To reproduce

- Open drop-in UI
- Add paypal as payment method
- Login paypal acc
- Failed return to app

### Expected behavior

Should able back to app

**Comment by sshropshire** [comment] 2023-08-24 19:44
Hi @Chaos2805 thanks for using the Braintree SDK. For context, we stopped lowercasing the `applicationId` used for creating a custom URL scheme because capital letters are still valid URL characters according to [RFC 2396](https://stackoverflow.com/a/3641782).

Can you provide a snippet of your `AndroidManifest.xml`?

**Comment by Chaos2805** [comment] 2023-08-25 09:08
<img width="1105" alt="image" src="https://github.com/braintree/braintree-android-drop-in/assets/21195683/4d4938ae-e697-4f2c-bda0-d773f4b351b6">
@sshropshire

**Comment by Chaos2805** [comment] 2023-08-27 08:40
@sshropshire any update and able to fix it shortly? As we need update our app this week. Playstore required com.braintreepayments.api:data-collector update to atleast v4.31.0, but hit this issue after update it and make PayPal unable to function properly

**Comment by Chaos2805** [comment] 2023-08-28 01:25
@sarahkoop can you assist on this?

**Comment by sarahkoop** [comment] 2023-08-28 14:14
@Chaos2805 We are working on a fix for this issue. We will post an update here when it's available.

**Comment by Chaos2805** [comment] 2023-09-04 05:07
@sshropshire @sarahkoop Can I get updates for this issue?

**Comment by sshropshire** [comment] 2023-09-06 14:39
@Chaos2805 thanks for your patience. We'll be providing an update soon. In the meantime, you can preview our [4.37.1-SNAPSHOT](https://github.com/braintree/braintree_android#adding-it-to-your-project) release to ensure that the issue is resolved.

**Comment by Chaos2805** [comment] 2023-09-06 15:36
Hi @sshropshire , I tried [4.37.1-SNAPSHOT](https://github.com/braintree/braintree_android#adding-it-to-your-project) release and it working now

**Comment by sarahkoop** [comment] 2023-09-25 14:34
Hi @Chaos2805 - This fix has been released in version `4.38.2` of the Braintree Android SDK and version `6.13.0` of the Drop-in SDK. Closing this as resolved but please re-open if you continue to experience issues!

**Closed by sarahkoop** 2023-09-25 14:34 UTC
