### ISSUE TITLE
DropIn PayPal process payment issue

### ISSUE THREAD

**Issue by lcervelli** [braintree/braintree-android-drop-in#379] opened 2022-12-15 12:22 UTC
### General information

* SDK/Library version: 6.5.0, 6.5.1, 6.6.0, 6.7.0
* Environment: PayPal SandBox
* Android Version and Device: Samsung Galaxy Tab S6 with Android 12

### Issue description

I'm using DropIn on Android platform to perform Payment by PayPal. Please find below the steps:

1. Start activity that shows DropIn
2. Select PayPal as Payment process from DropIn UI
3. as soon as the PayPal payment process is complete the PayPal screen is closed and my activity receives: User canceled DropIn (event is received as error: UserCanceledException)
5. Using standard Credit Card payment flow works fine

Thanks and regards.

**Comment by sshropshire** [comment] 2022-12-16 16:15
@lcervelli thanks for using the Braintree SDK for Android. I'm unable to produce this in our demo application. Can you provide more details on your integration? Specifically some code snippets showing how you're instantiating `DropInClient` and invoking `launchDropIn()`?

Also if you could provide a video of the unexpected behavior that would be most helpful in resolving the issue.

**Comment by lcervelli** [comment] 2022-12-19 08:20
Please find below the code used to trigger the drop in:

class BraintreePaymentsActivity : AppCompatActivity(), DropInListener {
    private lateinit var dropInClient: DropInClient

    private var token: String = ""
    private var price: Double = Double.MIN_VALUE
    private var showDropIn = true

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        savedInstanceState?.apply {
            token = getString(TOKEN_KEY, "")
            price = getDouble(PRICE_KEY, Double.MIN_VALUE)
        } ?: run {
            intent.extras?.apply {
                token = getString(TOKEN_KEY, "")
                price = getDouble(PRICE_KEY, Double.MIN_VALUE)
            }
        }
        dropInClient = DropInClient(this@BraintreePaymentsActivity, if (price > 0.0) token else "")
        dropInClient.setListener(this@BraintreePaymentsActivity)
    }

    override fun onStart() {
        super.onStart()
        showDropIn()
    }

    override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        outState.apply {
            putString(TOKEN_KEY, token)
            putDouble(PRICE_KEY, price)
        }
    }

    private fun createThreeDSecureRequest(): ThreeDSecureRequest = ThreeDSecureRequest().apply {
        amount = price.toString()
        versionRequested = ThreeDSecureRequest.VERSION_2
    }

    private fun getDropInRequest(): DropInRequest = DropInRequest().apply {
        if (isFeatureEnabled(Features.Feature.ENABLE_PAYPAL_FOR_BRAINTREE)) {
            payPalRequest = PayPalCheckoutRequest(price.toString())
        } else {
            isPayPalDisabled = true
        }
        maskCardNumber = true
        maskSecurityCode = true
        allowVaultCardOverride = false
        isVaultManagerEnabled = false
        threeDSecureRequest = createThreeDSecureRequest()
    }

    private fun showDropIn() {
        if (showDropIn) {
            dropInClient.run {
                launchDropIn(getDropInRequest())
                showDropIn = false
            }
        }
    }

    override fun onDropInSuccess(dropInResult: DropInResult) {
        val data = Intent()
        val bundle = Bundle()
        bundle.putParcelable(DropInResult.EXTRA_DROP_IN_RESULT, dropInResult)
        data.putExtras(bundle)
        setResult(Activity.RESULT_OK, data)
        finish()
    }

    override fun onDropInFailure(error: java.lang.Exception) {
        if (error is UserCanceledException) {
            setResult(Activity.RESULT_CANCELED)
        } else {
            setResult(BraintreePurchaseProceedListener.FAILED_UNEXPECTED_ERROR)
        }
        finish()
    }
}

But before the payment is finished my **onDropInFailure** is triggered

**Comment by sshropshire** [comment] 2022-12-19 20:28
@lcervelli interesting everything looks standard. Out of curiosity, can we try calling `showDropIn()` in `onResume()` to see if that helps to resolve the issue?

Also I would replace this line..

```kotlin
dropInClient = DropInClient(this@BraintreePaymentsActivity, if (price > 0.0) token else "")
```
with:
```kotlin
dropInClient = DropInClient(this@BraintreePaymentsActivity, token)
```

An empty string for a token could cause unexpected behavior in any scenario.

**Comment by lcervelli** [comment] 2022-12-19 20:47
Thanks for feedback I'll try to put the code in **onResume** and I get you back with the result.
About your suggestion an empty token, if I'm not wrong, should provide a call to ** onDropInFailure** having message: **Authorization provided is invalid**, that what I would like to have.

**Comment by lcervelli** [comment] 2022-12-20 08:26
Attached you'll find the video with reporting the issue.

After payment before showing the Map our software receives the callback: ** onDropInFailure** due to ** UserCanceledException**
Tomorrow I'll test the code moved from onStart to onResume

Thanks

https://user-images.githubusercontent.com/6418008/208618894-b1a3de5c-1815-4f64-909e-b7857ade457b.mp4

**Comment by lcervelli** [comment] 2022-12-22 17:38
I tried to move the show drop-in from onStart to onResume, but I had the same result.
Thanks

**Comment by lcervelli** [comment] 2023-01-03 15:14
We also tried to use the latest version of the lib: 6.6.0 but the result is the same.
Have you any news about that?

**Comment by sshropshire** [comment] 2023-01-03 20:13
@lcervelli we added updates to some of our 3rd party dependencies for Google Play store compliance in our most recent release.

Your app's integration looks standard. At a glance I can't determine what the root issue could be. Would you mind setting a breakpoint [here](https://github.com/braintree/braintree-android-drop-in/blob/da1d2a2a2d66e55c90a98b11ae80426a91c3914c/Drop-In/src/main/java/com/braintreepayments/api/DropInActivity.java#L453) to gather more info? I want to verify if the browser switch result is being parsed correctly.

**Comment by lcervelli** [comment] 2023-01-05 16:41
Thanks for reply, I'll try to do it starting from next Monday.
Thanks

**Comment by lcervelli** [comment] 2023-01-09 13:55
Hi @sshropshire,
I put the breakpoint where you suggested and I saw that only when I show the dropIn the API is triggered. I was expecting to be linked there also when I come back from the purchase flow but I was wrong.
Do you think I can try something else?
Thanks.

**Comment by lcervelli** [comment] 2023-01-10 09:19
Today morning I also tried to use your latest version but I got the same result.

**Comment by sshropshire** [comment] 2023-01-10 15:55
@lcervelli I believe they must be lowercase. I can't find a definitive source but this [stackoverflow post](https://askubuntu.com/a/1262555) does reference a Debian Policy Manual.

**Comment by lcervelli** [comment] 2023-01-11 07:42
Reported by Android Doc:

_Although the application ID looks like a traditional Java or Kotlin package name, the naming rules for the application ID are a bit more restrictive:

- It must have at least two segments (one or more dots).
- Each segment must start with a letter.
- All characters must be alphanumeric or an underscore [a-zA-Z0-9_]._

The latest bullet talk about the possibility to use also uppercase letters: **[a-zA-Z0-9_]**

https://developer.android.com/studio/build/configure-app-module

The main issue is related to the fact that my App has an applicationID having uppercase letters and in manifest configuration I specify:

`<data android:scheme="..." />`

using lowercase letters, due to that Paypal payment is not able to work.

In an old version of your library it works even if **applicationID** and **data android:scheme** were different due to lowercase and uppercase letters.

Thanks

**Comment by lcervelli** [comment] 2023-01-13 10:12
@sshropshire 
Have you any news about my latest comment?

Thanks

**Comment by sshropshire** [comment] 2023-01-17 14:22
@lcervelli the scheme and the application ID can be different. The breakpoint [I mentioned earlier](https://github.com/braintree/braintree-android-drop-in/issues/379#issuecomment-1370183136) should be hit before DropIn delivers a cancelation result. What is the value for `error.message` at the breakpoint? That may help us pinpoint the exact cause of the error.

**Comment by lcervelli** [comment] 2023-01-18 08:38
Hi @sshropshire please find below the detailed flow specs I had:

- Press my app button to open drop-in: as soon as I press the UI button the code triggers **DropInActivity**.onDropInResult and the error reported is: **com.braintreepayments.api.UserCanceledException: User canceled PayPal**
- Select from drop-in paypal payment method. As soon as the payment flow is done code triggers: **DropInClient**.onDropInResult (and not DropInActivity) where the error reported is: **com.braintreepayments.api.UserCanceledException: User canceled DropIn**

So as described in my previous post at the end of the purchase flow the point where you suggest to put the breakpoint is not triggered.

One more thing, I created a very simple app where if you use your latest lib drop-in version: 6.7.0, and set application id like: it.myname.myTestAppId in build.gradle Module app:

`applicationId "it.myname.myTestAppId"`

and set schema filter to: it.myname.mytestappid in manifest file:

```
<activity
            android:name=".BraintreePaymentsActivity"
            android:exported="true"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <data android:scheme="it.myname.mytestappid" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
</activity>
```

I have exactly the same behaviour I described in our conversation.

By simply changing the **applicationId to all lowercase letters** I get the desired behaviour.

If you want I can also provide the full demo code of this simple app, the only thing that you should provide from your side is the token.

Thanks and regards.

**Comment by lcervelli** [comment] 2023-01-18 16:06
Hi @sshropshire,
Probably I could have found the issue that did not permit to me to complete the purchase flow:

[https://github.com/braintree/braintree-android-drop-in/blob/master/Drop-In/src/main/AndroidManifest.xml#L18](url)

This line of xml code assume that applicationId is lowercase but it's not true due to:

https://developer.android.com/studio/build/configure-app-module

Thanks and regards.

**Comment by sshropshire** [comment] 2023-01-18 16:24
Hi @lcervelli I completely forgot that we lowercase the `applicationId` in [BraintreeClient by default](https://github.com/braintree/braintree_android/blob/29b64ca0a41c5894d4e61184573b2bf41508a984/BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java#L36). That would explain why lowercasing the scheme works in this scenario. This happens in our core [braintree_android](https://github.com/braintree/braintree_android) library. The workaround is not ideal, but it will work.

We may want to offer the ability to set a custom url scheme in the future as a parameter in `DropInRequest` to eliminate the need for this workaround.

**Comment by lcervelli** [comment] 2023-01-19 07:52
Hi @sshropshire,
Have you any idea about when a new lib with the mentioned feature will be available?

Thanks and regards.

**Comment by sshropshire** [comment] 2023-01-20 21:29
Hey @lcervelli can you re-write your `AndroidManifest.xml` to match the code snippet below as a workaround?

```xml
<activity
  android:name=".BraintreePaymentsActivity"
  android:exported="true"
  android:launchMode="singleTask" />
<activity
  android:name="com.braintreepayments.api.DropInActivity"
  android:exported="true"
  tools:node="merge">
  <intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="it.myname.mytestappid.braintree" />

    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
  </intent-filter>
</activity>
```

This will add an intent filter to `DropInActivity` which is the intended deep link target. I realized `BraintreePaymentsActivity` may be intercepting the deep link.

Note the data scheme will still need to be lowercase for now. Let me know if this works.

**Comment by pavan-tri** [comment] 2023-01-21 10:42
The suggest method works @sshropshire

**Comment by lcervelli** [comment] 2023-01-21 15:13
@sshropshire I have already implemented it to enable Paypal in my latest App update.

Thanks and regards for your suggestion.

**Comment by sshropshire** [comment] 2023-01-23 16:48
@pavan-tri @lcervelli awesome! We may provide an update that will prevent the need for a workaround. It appears we are unnecessarily lowercasing the application id internally. In the future, we should allow camel cased package names.

**Comment by sshropshire** [comment] 2023-02-15 22:15
@lcervelli @pavan-tri camel cased package names are now allowed in version [6.8.0](https://github.com/braintree/braintree-android-drop-in/blob/6.8.0/CHANGELOG.md#680). Underscores are still prohibited because they are not considered valid URL scheme characters in [RFC 2396](https://stackoverflow.com/a/3641782).

**Closed by sshropshire** 2023-02-15 22:15 UTC
